// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6NK97cBdX6MzwoDRJM0_YAREqHy5yRds',
    appId: '1:283428213458:web:2c550fcb217f7b32dc130b',
    messagingSenderId: '283428213458',
    projectId: 'tiemtraanlanh',
    authDomain: 'tiemtraanlanh.firebaseapp.com',
    storageBucket: 'tiemtraanlanh.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCp2_8rxrDYYgWOqKGk-_5-P5ilttl7m2A',
    appId: '1:283428213458:android:aff415460c87edfcdc130b',
    messagingSenderId: '283428213458',
    projectId: 'tiemtraanlanh',
    storageBucket: 'tiemtraanlanh.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuUQufAoS5-cNcbUhUGH3eD4T5bQXOAzk',
    appId: '1:283428213458:ios:14eb2b8f5823f230dc130b',
    messagingSenderId: '283428213458',
    projectId: 'tiemtraanlanh',
    storageBucket: 'tiemtraanlanh.firebasestorage.app',
    iosBundleId: 'com.example.tiemtraAnlanh',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuUQufAoS5-cNcbUhUGH3eD4T5bQXOAzk',
    appId: '1:283428213458:ios:14eb2b8f5823f230dc130b',
    messagingSenderId: '283428213458',
    projectId: 'tiemtraanlanh',
    storageBucket: 'tiemtraanlanh.firebasestorage.app',
    iosBundleId: 'com.example.tiemtraAnlanh',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6NK97cBdX6MzwoDRJM0_YAREqHy5yRds',
    appId: '1:283428213458:web:ccec617487d39779dc130b',
    messagingSenderId: '283428213458',
    projectId: 'tiemtraanlanh',
    authDomain: 'tiemtraanlanh.firebaseapp.com',
    storageBucket: 'tiemtraanlanh.firebasestorage.app',
  );
}
